# =========================================================
# Q's minimal PowerShell profile
# zoxide + starship + optional fzf
# =========================================================

# ---------- helpers ----------

function Has-Cmd {
    param([Parameter(Mandatory)][string]$Name)
    return [bool](Get-Command $Name -ErrorAction SilentlyContinue)
}

# ---------- basic env ----------

$env:EDITOR = "code"
$env:VISUAL = "code"
$env:STARSHIP_CONFIG = "$HOME\.config\starship.toml"

try {
    [Console]::InputEncoding  = [System.Text.UTF8Encoding]::new()
    [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
    $OutputEncoding = [System.Text.UTF8Encoding]::new()
} catch {}

# ---------- PSReadLine ----------

try {
    Import-Module PSReadLine -ErrorAction Stop

    Set-PSReadLineOption -EditMode Windows
    Set-PSReadLineOption -BellStyle None
    Set-PSReadLineOption -PredictionSource History
    Set-PSReadLineOption -PredictionViewStyle ListView

    Set-PSReadLineKeyHandler -Key Tab    -Function MenuComplete
    Set-PSReadLineKeyHandler -Key Ctrl+d -Function DeleteCharOrExit
    Set-PSReadLineKeyHandler -Key Ctrl+r -Function ReverseSearchHistory
    Set-PSReadLineKeyHandler -Key Ctrl+f -Function ForwardWord
    Set-PSReadLineKeyHandler -Key Ctrl+b -Function BackwardWord
    Set-PSReadLineKeyHandler -Key Ctrl+l -Function ClearScreen
} catch {
    Write-Warning "PSReadLine not available or failed to configure."
}

# ---------- tiny aliases ----------

function ll { Get-ChildItem -Force @args }
function la { Get-ChildItem -Force @args }
function .. { Set-Location .. }
function ... { Set-Location ..\.. }

function reload {
    . $PROFILE.CurrentUserAllHosts
}

function prof {
    if (Has-Cmd code) {
        code $PROFILE.CurrentUserAllHosts
    } else {
        notepad $PROFILE.CurrentUserAllHosts
    }
}

# ---------- zoxide ----------

if (Has-Cmd zoxide) {
    Invoke-Expression (& { (zoxide init powershell | Out-String) })
}

# ---------- fzf: installed but mostly passive ----------

if (Has-Cmd fzf) {
    $env:FZF_DEFAULT_OPTS = "--height 40% --layout=reverse --border"

    function fcd {
        $dir = Get-ChildItem -Directory -Recurse -ErrorAction SilentlyContinue |
            Select-Object -ExpandProperty FullName |
            fzf

        if ($dir) {
            Set-Location $dir
        }
    }

    function fh {
        Get-Content (Get-PSReadLineOption).HistorySavePath |
            fzf |
            Set-Clipboard
    }
}

# ---------- starship prompt ----------

if (Has-Cmd starship) {
    Invoke-Expression (&starship init powershell)
}
# >>> mozi compat install >>>
# Generated by `mozi compat install --shell-profile`. Safe to remove.
# Override Windows system32 find/grep with moz(i) shims.
$_mozi_compat_bin = 'C:\Users\Rust\.local/bin'
function find { & (Join-Path $_mozi_compat_bin 'find.exe') @args }
function grep { & (Join-Path $_mozi_compat_bin 'grep.exe') @args }
# <<< mozi compat install <<<
