// `luban completion <shell>` — emit shell-specific tab completion script.
//
// Today only `clink` is implemented (cmd.exe with the clink enhancement).
// Future shells: bash, zsh, pwsh, fish.

#include <cstdio>
#include <iostream>
#include <string_view>

#include "../cli.hpp"
#include "../log.hpp"

namespace luban::commands {

namespace {

// clink Lua argmatcher script. Emitted on stdout — user redirects to
// %LOCALAPPDATA%\clink\completions\luban.lua (or scripts dir).
//
// Manual maintenance: when a new verb / flag lands, update this string
// alongside. Static authoring beats runtime introspection — clink loads
// the script at cmd startup and uses it for every prompt; stable strings
// are faster than spawning luban for completions.
//
// Reference: https://chrisant996.github.io/clink/clink.html#argument-completion
constexpr std::string_view kClinkScript = R"LUA(-- luban tab completion for clink (cmd.exe enhancement)
-- Generated by `luban completion clink`. Re-generate after upgrading luban.
-- Install: place under any of clink's script dirs. Most commonly:
--   %LOCALAPPDATA%\clink\completions\luban.lua
-- Then `clink reload` (or open a new cmd window).

local cmds = {
    "add", "build", "completion", "describe", "doctor", "env",
    "help", "new", "remove", "run", "search", "self", "setup",
    "shim", "sync", "target", "which",
}

-- Top-level: luban -V/--version | -v/--verbose | -h/--help | <command>
clink.argmatcher("luban")
    :addflags("-V", "--version", "-h", "--help", "-v", "--verbose")
    :addarg(cmds)

-- Per-command argmatchers. clink lets us define them as a separate
-- argmatcher attached to the verb name; it activates after the verb word.

-- luban new app|lib <name>
clink.argmatcher("luban", "new")
    :addflags("--no-build", "--at")
    :addarg("app", "lib")

-- luban target add lib|exe <name>  |  luban target remove <name>
clink.argmatcher("luban", "target")
    :addarg("add", "remove")
    :addarg("lib", "exe")

-- luban self update | uninstall [--yes] [--keep-data]
clink.argmatcher("luban", "self")
    :addflags("--yes", "--keep-data")
    :addarg("update", "uninstall")

-- luban env [--apply] [--user] [--unset-user]
clink.argmatcher("luban", "env")
    :addflags("--apply", "--user", "--unset-user")

-- luban setup [--only <names>] [--force] [--dry-run] [--refresh-buckets]
clink.argmatcher("luban", "setup")
    :addflags("--only", "--force", "--dry-run", "--refresh-buckets")

-- luban describe [--json]
clink.argmatcher("luban", "describe")
    :addflags("--json")

-- luban build [--preset <name>] [--at <dir>]
clink.argmatcher("luban", "build")
    :addflags("--preset", "--at")

-- luban completion <shell>
clink.argmatcher("luban", "completion")
    :addarg("clink")  -- bash / zsh / pwsh: see github.com/Coh1e/luban/issues

-- Verbs without flags or with only positional input — use defaults
-- (file/path completion or no completion). Listed for explicitness:
--   add <pkg>  remove <pkg>  sync  search <pattern>
--   run <cmd> [args...]   which <alias>   doctor   shim   help [<topic>]
)LUA";

int run_completion(const cli::ParsedArgs& a) {
    if (a.positional.empty()) {
        log::err("usage: luban completion <shell>");
        log::info("supported: clink");
        return 2;
    }
    const std::string& shell = a.positional[0];

    if (shell == "clink") {
        std::cout << kClinkScript;
        return 0;
    }

    log::errf("unsupported shell: {}", shell);
    log::info("supported: clink");
    log::info("(bash / zsh / pwsh / fish welcome — see github.com/Coh1e/luban/issues)");
    return 2;
}

}  // namespace

void register_completion() {
    cli::Subcommand c;
    c.name = "completion";
    c.help = "emit shell completion script (clink today; bash/zsh/pwsh next)";
    c.group = "advanced";
    c.long_help =
        "  Print a shell-specific tab-completion script to stdout.\n"
        "\n"
        "  Today: `luban completion clink` outputs a Lua argmatcher script\n"
        "  for cmd.exe with clink loaded. Pipe it into a file under clink's\n"
        "  scripts dir; clink loads it automatically on next cmd start.\n"
        "\n"
        "  bash / zsh / pwsh / fish: tracked at github.com/Coh1e/luban/issues.";
    c.n_positional = 1;
    c.positional_names = {"shell"};
    c.examples = {
        "luban completion clink > %LOCALAPPDATA%\\clink\\completions\\luban.lua\tInstall for clink-enhanced cmd.exe",
        "luban completion clink | clink set-script\tFuture: pipe-friendly install",
    };
    c.run = run_completion;
    cli::register_subcommand(std::move(c));
}

}  // namespace luban::commands
