// `luban completion <shell>` — emit shell-specific tab completion script.
//
// Supported shells: clink (cmd.exe enhancement), bash, zsh, fish, powershell.
//
// Each emitter is a static string template (some with the verb list spliced
// in once for DRY-ness). Manual authoring beats runtime introspection here:
// shells load the completion script once at session start, so a stable
// string is much faster than spawning `luban` for every Tab press. The cost
// is that adding a verb / flag means updating this file too — the alternative
// would couple every shell to luban's internal Subcommand registry which is
// neither shell-friendly nor portable.
//
// To keep maintenance manageable, only verbs + their named flags are scripted.
// Positional values that would require luban-side state (e.g., listing
// installed component aliases for `luban which`) are left as default
// path-completion or unspecified; users still get verb / flag autocomplete.

#include <cstdio>
#include <iostream>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

#include "../cli.hpp"
#include "../log.hpp"

namespace luban::commands {

namespace {

// Top-level verb list. Keep alphabetical so each shell's emitter can re-use
// the same string without per-shell ordering quirks. Drives every script
// below; bumping this here updates all 5 shells.
constexpr std::string_view kVerbsSpaceSep =
    "add build completion describe doc doctor env new remove run "
    "search self setup shim specs sync target which";

// Verbs as `'a' 'b' 'c'` (space-separated, single-quoted). Used by zsh's
// _values which takes a space-separated list of completion options.
std::string verbs_zsh_quoted() {
    std::string s(kVerbsSpaceSep);
    std::string out;
    out.reserve(s.size() + 64);
    size_t start = 0;
    bool first = true;
    while (start <= s.size()) {
        size_t end = s.find(' ', start);
        if (end == std::string::npos) end = s.size();
        if (!first) out += " ";
        first = false;
        out += "'" + s.substr(start, end - start) + "'";
        if (end == s.size()) break;
        start = end + 1;
    }
    return out;
}

// Verbs as `'a', 'b', 'c'` (comma-separated, single-quoted). Used by
// PowerShell's array literal `@('a', 'b', 'c')`. Same data, different
// delimiter.
std::string verbs_pwsh_quoted() {
    std::string s(kVerbsSpaceSep);
    std::string out;
    out.reserve(s.size() + 64);
    size_t start = 0;
    bool first = true;
    while (start <= s.size()) {
        size_t end = s.find(' ', start);
        if (end == std::string::npos) end = s.size();
        if (!first) out += ", ";
        first = false;
        out += "'" + s.substr(start, end - start) + "'";
        if (end == s.size()) break;
        start = end + 1;
    }
    return out;
}

// ---- clink (cmd.exe + clink) -----------------------------------------------

// Verbs as `"a", "b", "c"` (comma + double-quoted) for Lua table literal.
// Same data as kVerbsSpaceSep, just delimited differently. Sharing the source
// keeps clink in sync with bash/zsh/fish/pwsh — adding a new verb only
// requires touching kVerbsSpaceSep above.
std::string verbs_clink_quoted() {
    std::string s(kVerbsSpaceSep);
    std::string out;
    out.reserve(s.size() + 64);
    size_t start = 0;
    bool first = true;
    while (start <= s.size()) {
        size_t end = s.find(' ', start);
        if (end == std::string::npos) end = s.size();
        if (!first) out += ", ";
        first = false;
        out += "\"" + s.substr(start, end - start) + "\"";
        if (end == s.size()) break;
        start = end + 1;
    }
    return out;
}

constexpr std::string_view kClinkHead = R"LUA(-- luban tab completion for clink (cmd.exe enhancement)
-- Generated by `luban completion clink`. Re-generate after upgrading luban.
-- Install: drop into any of clink's script dirs, commonly:
--   %LOCALAPPDATA%\clink\completions\luban.lua
-- Then `clink reload` (or open a new cmd window).

local cmds = { )LUA";

constexpr std::string_view kClinkTail = R"LUA( }

clink.argmatcher("luban")
    :addflags("-V", "--version", "-h", "--help", "-v", "--verbose")
    :addarg(cmds)

-- Per-verb argmatchers. Each activates after the verb word is on the line.

clink.argmatcher("luban", "new")
    :addflags("--no-build", "--at", "--target", "--with-specs")
    :addarg("app", "lib")

clink.argmatcher("luban", "target")
    :addarg("add", "remove")
    :addarg("lib", "exe")

clink.argmatcher("luban", "self")
    :addflags("--yes", "--keep-data")
    :addarg("update", "uninstall")

clink.argmatcher("luban", "env")
    :addflags("--user", "--unset-user", "--print", "--shell", "--msvc-init", "--msvc-clear", "--arch")

clink.argmatcher("luban", "setup")
    :addflags("--only", "--with", "--without", "--force", "--dry-run")

clink.argmatcher("luban", "describe")
    :addflags("--json", "--host")

clink.argmatcher("luban", "doctor")
    :addflags("--strict", "--json")

clink.argmatcher("luban", "build")
    :addflags("--preset", "--at")

clink.argmatcher("luban", "doc")
    :addflags("--open", "--clean")

clink.argmatcher("luban", "specs")
    :addarg("init", "sync", "new", "status")

clink.argmatcher("luban", "shim")
    :addflags("--force")

clink.argmatcher("luban", "completion")
    :addarg("clink", "bash", "zsh", "fish", "powershell")
)LUA";

// ---- bash ------------------------------------------------------------------

// Bash completion. The function name `_luban` is conventional; the trailing
// `complete -F _luban luban` registers it. We use compgen for the verb list
// and per-verb flag fanout via a case statement.
std::string emit_bash() {
    std::ostringstream s;
    s << R"BASH(# luban tab completion for bash.
# Generated by `luban completion bash`. Source manually or drop under
# /etc/bash_completion.d/, ~/.bash_completion.d/, or
# ~/.local/share/bash-completion/completions/luban.

_luban() {
    local cur prev verbs
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    verbs=")BASH";
    s << kVerbsSpaceSep << R"BASH("

    # Position 1: top-level verb (or top-level flags).
    if [ "$COMP_CWORD" -eq 1 ]; then
        if [[ "$cur" == -* ]]; then
            COMPREPLY=( $(compgen -W "-V --version -h --help -v --verbose" -- "$cur") )
        else
            COMPREPLY=( $(compgen -W "$verbs" -- "$cur") )
        fi
        return 0
    fi

    # The verb is COMP_WORDS[1]. Branch on it for per-verb flags / positional.
    local verb="${COMP_WORDS[1]}"
    case "$verb" in
        new)        COMPREPLY=( $(compgen -W "--no-build --at --target --with-specs app lib" -- "$cur") );;
        target)     COMPREPLY=( $(compgen -W "add remove lib exe" -- "$cur") );;
        self)       COMPREPLY=( $(compgen -W "--yes --keep-data update uninstall" -- "$cur") );;
        env)        COMPREPLY=( $(compgen -W "--user --unset-user --print --shell --msvc-init --msvc-clear --arch bash cmd powershell" -- "$cur") );;
        setup)      COMPREPLY=( $(compgen -W "--only --with --without --force --dry-run" -- "$cur") );;
        describe)   COMPREPLY=( $(compgen -W "--json --host" -- "$cur") );;
        doctor)     COMPREPLY=( $(compgen -W "--strict --json" -- "$cur") );;
        build)      COMPREPLY=( $(compgen -W "--preset --at" -- "$cur") );;
        doc)        COMPREPLY=( $(compgen -W "--open --clean" -- "$cur") );;
        specs)      COMPREPLY=( $(compgen -W "init sync new status" -- "$cur") );;
        shim)       COMPREPLY=( $(compgen -W "--force" -- "$cur") );;
        completion) COMPREPLY=( $(compgen -W "clink bash zsh fish powershell" -- "$cur") );;
        *)          COMPREPLY=();;
    esac
}
complete -F _luban luban
)BASH";
    return s.str();
}

// ---- zsh -------------------------------------------------------------------

// Zsh's _arguments DSL is rich but verbose. We use a compdef function and
// per-verb subcommand definitions via _luban_<verb> helpers. Drop the file
// under any dir on $fpath named `_luban` (or autoload-on-first-use via
// `compinit`).
std::string emit_zsh() {
    std::ostringstream s;
    s << R"ZSH(#compdef luban
# luban tab completion for zsh.
# Generated by `luban completion zsh`. Save to a file named `_luban` in any
# directory on $fpath (e.g., ~/.zsh/completions/_luban), then ensure that
# dir is added via `fpath=(~/.zsh/completions $fpath)` before `compinit`.

_luban() {
    local context state state_descr line
    typeset -A opt_args

    _arguments -C \
        '(-V --version)'{-V,--version}'[show version and exit]' \
        '(-h --help)'{-h,--help}'[show help and exit]' \
        '(-v --verbose)'{-v,--verbose}'[verbose output]' \
        '1: :_luban_verbs' \
        '*::arg:->args'

    case $state in
        args)
            case $words[1] in
                new)        _values 'flag' --no-build --at --target --with-specs app lib ;;
                target)     _values 'arg' add remove lib exe ;;
                self)       _values 'flag' --yes --keep-data update uninstall ;;
                env)        _values 'flag' --user --unset-user --print --shell --msvc-init --msvc-clear --arch ;;
                setup)      _values 'flag' --only --with --without --force --dry-run ;;
                describe)   _values 'flag' --json --host ;;
                doctor)     _values 'flag' --strict --json ;;
                build)      _values 'flag' --preset --at ;;
                doc)        _values 'flag' --open --clean ;;
                specs)      _values 'sub' init sync new status ;;
                shim)       _values 'flag' --force ;;
                completion) _values 'shell' clink bash zsh fish powershell ;;
            esac
            ;;
    esac
}

_luban_verbs() {
    _values 'verb' )ZSH";
    s << verbs_zsh_quoted() << R"ZSH(
}

_luban "$@"
)ZSH";
    return s.str();
}

// ---- fish ------------------------------------------------------------------

// Fish has a clean per-line `complete` syntax. Lots of lines but each is
// trivially understandable. Drop under ~/.config/fish/completions/luban.fish.
std::string emit_fish() {
    std::ostringstream s;
    s << R"FISH(# luban tab completion for fish.
# Generated by `luban completion fish`. Save under
#   ~/.config/fish/completions/luban.fish
# Fish picks it up automatically on next shell start.

# Top-level verbs
complete -c luban -n '__fish_use_subcommand' -a 'add'        -d 'add a vcpkg dependency'
complete -c luban -n '__fish_use_subcommand' -a 'build'      -d 'cmake configure + ninja build'
complete -c luban -n '__fish_use_subcommand' -a 'completion' -d 'emit shell completion script'
complete -c luban -n '__fish_use_subcommand' -a 'describe'   -d 'system + project state'
complete -c luban -n '__fish_use_subcommand' -a 'doc'        -d 'generate API docs (doxygen wrap)'
complete -c luban -n '__fish_use_subcommand' -a 'doctor'     -d 'health report'
complete -c luban -n '__fish_use_subcommand' -a 'env'        -d 'env state / HKCU registration'
complete -c luban -n '__fish_use_subcommand' -a 'new'        -d 'scaffold a new C++ project'
complete -c luban -n '__fish_use_subcommand' -a 'remove'     -d 'remove a vcpkg dependency'
complete -c luban -n '__fish_use_subcommand' -a 'run'        -d 'run a luban-managed exe'
complete -c luban -n '__fish_use_subcommand' -a 'search'     -d 'vcpkg search wrapper'
complete -c luban -n '__fish_use_subcommand' -a 'self'       -d 'manage luban itself'
complete -c luban -n '__fish_use_subcommand' -a 'setup'      -d 'install toolchain components'
complete -c luban -n '__fish_use_subcommand' -a 'shim'       -d 'regenerate bin shims'
complete -c luban -n '__fish_use_subcommand' -a 'specs'      -d 'AGENTS.md + SAGE scaffold'
complete -c luban -n '__fish_use_subcommand' -a 'sync'       -d 'regenerate luban.cmake'
complete -c luban -n '__fish_use_subcommand' -a 'target'     -d 'add/remove cmake targets'
complete -c luban -n '__fish_use_subcommand' -a 'which'      -d 'resolve alias to absolute exe'

# Top-level flags
complete -c luban -s V -l version -d 'show version and exit'
complete -c luban -s h -l help    -d 'show help and exit'
complete -c luban -s v -l verbose -d 'verbose output'

# Per-verb flags / args
complete -c luban -n '__fish_seen_subcommand_from new'    -l no-build -l at -l target -l with-specs
complete -c luban -n '__fish_seen_subcommand_from new'    -a 'app lib'
complete -c luban -n '__fish_seen_subcommand_from target' -a 'add remove lib exe'
complete -c luban -n '__fish_seen_subcommand_from self'   -l yes -l keep-data
complete -c luban -n '__fish_seen_subcommand_from self'   -a 'update uninstall'
complete -c luban -n '__fish_seen_subcommand_from env'    -l user -l unset-user -l print -l shell -l msvc-init -l msvc-clear -l arch
complete -c luban -n '__fish_seen_subcommand_from setup'  -l only -l with -l without -l force -l dry-run
complete -c luban -n '__fish_seen_subcommand_from describe' -l json -l host
complete -c luban -n '__fish_seen_subcommand_from doctor' -l strict -l json
complete -c luban -n '__fish_seen_subcommand_from build'  -l preset -l at
complete -c luban -n '__fish_seen_subcommand_from doc'    -l open -l clean
complete -c luban -n '__fish_seen_subcommand_from specs'  -a 'init sync new status'
complete -c luban -n '__fish_seen_subcommand_from shim'   -l force
complete -c luban -n '__fish_seen_subcommand_from completion' -a 'clink bash zsh fish powershell'
)FISH";
    return s.str();
}

// ---- powershell ------------------------------------------------------------

// PowerShell uses Register-ArgumentCompleter. Drop the script in your
// $PROFILE or a module so it's loaded at shell start.
//
// Built in three concat'd pieces so the verb-list interpolation doesn't
// require breaking out of (and re-entering) a raw string literal — that
// trick is fragile because `)PWSH"` must match exactly and copy-paste
// errors silently leak C++ source text into the output.
std::string emit_powershell() {
    constexpr std::string_view kHead = R"PWSH(# luban tab completion for PowerShell (5.1+ / pwsh 7+).
# Generated by `luban completion powershell`. Add to your $PROFILE:
#   luban completion powershell | Out-String | Invoke-Expression
# (or save the output to a .ps1 and dot-source it from $PROFILE).

Register-ArgumentCompleter -Native -CommandName luban -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $tokens = $commandAst.CommandElements | ForEach-Object { $_.ToString() }
    $verb = if ($tokens.Count -ge 2) { $tokens[1] } else { '' }

    $verbs = @()PWSH";

    constexpr std::string_view kTail = R"PWSH()

    if ($commandAst.CommandElements.Count -le 2 -or
        ($commandAst.CommandElements.Count -eq 2 -and -not $wordToComplete.StartsWith('-'))) {
        # Position 1 — verb completion.
        $verbs | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
        return
    }

    $candidates = @()
    switch ($verb) {
        'new'        { $candidates = @('--no-build','--at','--target','--with-specs','app','lib') }
        'target'     { $candidates = @('add','remove','lib','exe') }
        'self'       { $candidates = @('--yes','--keep-data','update','uninstall') }
        'env'        { $candidates = @('--user','--unset-user','--print','--shell','--msvc-init','--msvc-clear','--arch') }
        'setup'      { $candidates = @('--only','--with','--without','--force','--dry-run') }
        'describe'   { $candidates = @('--json','--host') }
        'doctor'     { $candidates = @('--strict','--json') }
        'build'      { $candidates = @('--preset','--at') }
        'doc'        { $candidates = @('--open','--clean') }
        'specs'      { $candidates = @('init','sync','new','status') }
        'shim'       { $candidates = @('--force') }
        'completion' { $candidates = @('clink','bash','zsh','fish','powershell') }
        default      { return }
    }
    $candidates | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
    }
}
)PWSH";

    std::ostringstream s;
    s << kHead;
    s << verbs_pwsh_quoted();   // 'add', 'build', 'completion', ... (commas required)
    s << kTail;
    return s.str();
}

// ---- dispatch --------------------------------------------------------------

int run_completion(const cli::ParsedArgs& a) {
    if (a.positional.empty()) {
        log::err("usage: luban completion <shell>");
        log::info("supported: clink | bash | zsh | fish | powershell");
        return 2;
    }
    const std::string& shell = a.positional[0];

    if (shell == "clink") {
        std::cout << kClinkHead << verbs_clink_quoted() << kClinkTail;
        return 0;
    }
    if (shell == "bash")       { std::cout << emit_bash(); return 0; }
    if (shell == "zsh")        { std::cout << emit_zsh(); return 0; }
    if (shell == "fish")       { std::cout << emit_fish(); return 0; }
    if (shell == "powershell" || shell == "pwsh") { std::cout << emit_powershell(); return 0; }

    log::errf("unsupported shell: {}", shell);
    log::info("supported: clink | bash | zsh | fish | powershell");
    return 2;
}

}  // namespace

void register_completion() {
    cli::Subcommand c;
    c.name = "completion";
    c.help = "emit shell completion script (clink / bash / zsh / fish / powershell)";
    c.group = "advanced";
    c.long_help =
        "  Print a shell-specific tab-completion script to stdout.\n"
        "\n"
        "  clink       Lua argmatcher script for cmd.exe with clink loaded.\n"
        "              Pipe to %LOCALAPPDATA%\\clink\\completions\\luban.lua.\n"
        "  bash        compgen-based completion. Source from .bash_completion\n"
        "              or drop under /etc/bash_completion.d/.\n"
        "  zsh         _arguments-based completion. Save as `_luban` in any\n"
        "              dir on $fpath, then `compinit`.\n"
        "  fish        Per-line `complete` script. Save under\n"
        "              ~/.config/fish/completions/luban.fish.\n"
        "  powershell  Register-ArgumentCompleter script. Dot-source from\n"
        "              $PROFILE or `Out-String | Invoke-Expression` it.\n"
        "\n"
        "  Verb / flag list is hardcoded in the script — re-run after\n"
        "  upgrading luban to refresh.";
    c.n_positional = 1;
    c.positional_names = {"shell"};
    c.examples = {
        "luban completion clink > %LOCALAPPDATA%\\clink\\completions\\luban.lua\tInstall for clink",
        "luban completion bash > ~/.local/share/bash-completion/completions/luban\tInstall for bash",
        "luban completion fish > ~/.config/fish/completions/luban.fish\tInstall for fish",
        "luban completion powershell | Out-String | Invoke-Expression\tLoad in current pwsh session",
    };
    c.run = run_completion;
    cli::register_subcommand(std::move(c));
}

}  // namespace luban::commands
