// `luban env` — display environment state and (with --user) register
// luban's bin dir on HKCU PATH along with VCPKG_ROOT.
//
// The `--apply` activate-scripts mode and `LUBAN_DATA/CACHE/STATE/CONFIG`
// HKCU writes were removed in v0.2:
//   * Activate scripts had no users — `luban env --user` (rustup-style) is
//     the recommended path; CI uses `LUBAN_PREFIX=...` + the same command.
//   * LUBAN_* vars had zero on-disk consumers (no manifest / preset / port
//     ever read $env{LUBAN_DATA}); they only created visual clutter in
//     HKCU\Environment.
//
// Today HKCU writes only contain VCPKG_ROOT, which CMakePresets.json
// generated by `luban new` actually references.

#include <cstdio>
#include <iostream>

#include "../cli.hpp"
#include "../log.hpp"
#include "../paths.hpp"
#include "../registry.hpp"
#include "../win_path.hpp"

namespace luban::commands {

namespace {

namespace fs = std::filesystem;

// Legacy HKCU env vars luban used to write but no longer does. We still
// unset them in --unset-user so users upgrading from v0.1.x get a clean
// slate without manual reg cleanup.
constexpr const char* kLegacyHKCUVars[] = {
    "LUBAN_DATA", "LUBAN_CACHE", "LUBAN_STATE", "LUBAN_CONFIG",
};

int run_env(const cli::ParsedArgs& a) {
    fs::path bin = paths::bin_dir();

    log::infof("luban data dir : {}", paths::data_dir().string());
    log::infof("PATH directory : {}", bin.string());

    auto get_flag = [&](const char* name) {
        auto it = a.flags.find(name);
        return it != a.flags.end() && it->second;
    };

    // --user: rustup-style. Add bin_dir() to HKCU PATH and set VCPKG_ROOT
    // (the only HKCU env we still own). After this, any new shell sees the
    // luban toolchain through PATH; cmake presets resolve VCPKG_ROOT directly.
    if (get_flag("user")) {
        if (win_path::add_to_user_path(bin)) {
            log::okf("added {} to HKCU PATH", bin.string());
        } else {
            log::infof("{} already on HKCU PATH (no change)", bin.string());
        }

        // VCPKG_ROOT: CMakePresets.json uses
        //   $env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake
        // so the var must be in HKCU for users running cmake outside luban.
        auto recs = registry::load_installed();
        auto it = recs.find("vcpkg");
        if (it != recs.end() && !it->second.toolchain_dir.empty()) {
            fs::path vcpkg_root = paths::toolchain_dir(it->second.toolchain_dir);
            if (win_path::set_user_env("VCPKG_ROOT", vcpkg_root.string())) {
                log::okf("set HKCU VCPKG_ROOT = {}", vcpkg_root.string());
            }
        } else {
            log::info("VCPKG_ROOT not set (no vcpkg in registry; run `luban setup --with vcpkg` first)");
        }

        log::info("open a new shell for the changes to take effect.");
    }

    // --unset-user: reverse --user. bin_dir is luban-owned (<data>/bin),
    // so safe to remove from HKCU PATH; users who want luban-managed
    // toolchains in their shells should run --user again.
    if (get_flag("unset-user")) {
        if (win_path::remove_from_user_path(bin)) {
            log::okf("removed {} from HKCU PATH", bin.string());
        } else {
            log::infof("{} not on HKCU PATH (nothing to do)", bin.string());
        }
        for (const char* name : kLegacyHKCUVars) {
            win_path::unset_user_env(name);
        }
        win_path::unset_user_env("VCPKG_ROOT");
        log::ok("removed legacy LUBAN_* and VCPKG_ROOT from HKCU env");
    }

    return 0;
}

}  // namespace

void register_env() {
    cli::Subcommand c;
    c.name = "env";
    c.help = "show env state; register bin_dir on HKCU PATH (rustup-style)";
    c.group = "setup";
    c.long_help =
        "  Manage environment integration. With no flags, prints the bin dir\n"
        "  luban writes toolchain shims into (<data>/bin, luban-owned).\n"
        "\n"
        "  --user        Add bin_dir() to HKCU PATH + set HKCU VCPKG_ROOT.\n"
        "                After running this once, any new shell can run\n"
        "                cmake/clang/ninja/etc. through luban-managed shims.\n"
        "                The dir is luban-only (cargo's ~/.cargo/bin/ pattern);\n"
        "                luban.exe itself lives under ~/.local/bin/ (XDG).\n"
        "  --unset-user  Reverse --user. Also cleans up legacy LUBAN_* HKCU\n"
        "                env vars from pre-v0.2 installs.\n"
        "\n"
        "  Removed in v0.2: --apply (activate scripts) — `luban env --user`\n"
        "  is the canonical path; CI uses LUBAN_PREFIX=... + the same.";
    c.flags = {"user", "unset-user"};
    c.examples = {
        "luban env\tShow current env state",
        "luban env --user\tOne-time HKCU PATH registration (rustup-style)",
        "luban env --unset-user\tUndo the above + clean legacy vars",
    };
    c.run = run_env;
    cli::register_subcommand(std::move(c));
}

}  // namespace luban::commands
