// 1:1 port of luban_boot/commands/env.py + setup.py:_write_activate_scripts.
// `--apply` rewrites <data>/env/activate.{cmd,ps1,sh} + default.env.json.

#include <cstdio>
#include <fstream>
#include <iostream>
#include <sstream>

#include "../cli.hpp"
#include "../env_snapshot.hpp"
#include "../log.hpp"
#include "../paths.hpp"
#include "../registry.hpp"
#include "../win_path.hpp"

#include "json.hpp"

namespace luban::commands {

namespace {

namespace fs = std::filesystem;
using nlohmann::json;

void write_text(const fs::path& path, const std::string& content) {
    std::error_code ec;
    fs::create_directories(path.parent_path(), ec);
    std::ofstream out(path, std::ios::binary | std::ios::trunc);
    out.write(content.data(), static_cast<std::streamsize>(content.size()));
}

void write_activate_scripts() {
    fs::path env_dir = paths::env_dir();
    auto dirs = env_snapshot::path_dirs();
    auto extras = env_snapshot::env_dict();

    // CMD
    std::ostringstream cmd;
    cmd << "@echo off\r\n"
        << "rem ==== generated by luban \xe2\x80\x94 edit at your peril ====\r\n";
    for (auto& [k, v] : extras) cmd << "set \"" << k << "=" << v << "\"\r\n";
    {
        std::string joined;
        for (size_t i = 0; i < dirs.size(); ++i) {
            if (i) joined.push_back(';');
            joined += dirs[i].string();
        }
        cmd << "set \"PATH=" << joined << ";%PATH%\"\r\n";
    }
    write_text(env_dir / "activate.cmd", cmd.str());

    // PS1
    std::ostringstream ps1;
    ps1 << "# generated by luban \xe2\x80\x94 edit at your peril\r\n";
    for (auto& [k, v] : extras) ps1 << "$env:" << k << " = '" << v << "'\r\n";
    {
        std::string joined;
        for (size_t i = 0; i < dirs.size(); ++i) {
            if (i) joined.push_back(';');
            joined += dirs[i].string();
        }
        ps1 << "$env:PATH = '" << joined << ";' + $env:PATH\r\n";
    }
    write_text(env_dir / "activate.ps1", ps1.str());

    // SH
    std::ostringstream sh;
    sh << "# generated by luban \xe2\x80\x94 edit at your peril\n";
    for (auto& [k, v] : extras) sh << "export " << k << "=\"" << v << "\"\n";
    {
        std::string joined;
        for (size_t i = 0; i < dirs.size(); ++i) {
            if (i) joined.push_back(':');
            std::string s = dirs[i].string();
            for (auto& c : s) if (c == '\\') c = '/';
            joined += s;
        }
        sh << "export PATH=\"" << joined << ":$PATH\"\n";
    }
    write_text(env_dir / "activate.sh", sh.str());

    // default.env.json snapshot.
    json snapshot;
    json arr = json::array();
    for (auto& d : dirs) arr.push_back(d.string());
    snapshot["PATH_prepend"] = arr;
    json ex = json::object();
    for (auto& [k, v] : extras) ex[k] = v;
    snapshot["extras"] = ex;
    write_text(env_dir / "default.env.json", snapshot.dump(2) + "\n");
}

int run_env(const cli::ParsedArgs& a) {
    fs::path bin = paths::bin_dir();
    fs::path activate_cmd = paths::env_dir() / "activate.cmd";
    fs::path activate_ps1 = paths::env_dir() / "activate.ps1";
    fs::path activate_sh  = paths::env_dir() / "activate.sh";

    log::infof("luban data dir : {}", paths::data_dir().string());
    log::infof("PATH directory : {}", bin.string());

    std::error_code ec;
    if (fs::exists(activate_cmd, ec)) log::okf("cmd activate   : call \"{}\"", activate_cmd.string());
    if (fs::exists(activate_ps1, ec)) log::okf("pwsh activate  : . \"{}\"", activate_ps1.string());
    if (fs::exists(activate_sh, ec))  log::okf("bash activate  : source \"{}\"", activate_sh.string());
    if (!fs::exists(activate_cmd, ec) && !fs::exists(activate_ps1, ec) && !fs::exists(activate_sh, ec)) {
        log::warn("no activate scripts yet \xe2\x80\x94 run `luban env --apply`.");
    }

    auto get_flag = [&](const char* name) {
        auto it = a.flags.find(name);
        return it != a.flags.end() && it->second;
    };

    if (get_flag("apply")) {
        write_activate_scripts();
        log::okf("rewrote activate scripts in {}", paths::env_dir().string());
    }

    // --user：rustup-style 注 HKCU PATH + LUBAN_* + VCPKG_ROOT 用户 env。
    if (get_flag("user")) {
        if (win_path::add_to_user_path(bin)) {
            log::okf("added {} to HKCU PATH", bin.string());
        } else {
            log::infof("{} already on HKCU PATH (no change)", bin.string());
        }

        // LUBAN_DATA / LUBAN_CACHE / LUBAN_STATE / LUBAN_CONFIG —— 让 CMakePresets
        // 等用 $env{LUBAN_DATA} 引用 luban-managed paths。
        for (auto& [k, v] : env_snapshot::env_dict()) {
            if (win_path::set_user_env(k, v)) log::okf("set HKCU {} = {}", k, v);
        }

        // VCPKG_ROOT —— 让标准 CMakePresets `$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake`
        // 直接 work。从 installed.json 取 vcpkg 的 toolchain_dir。
        auto recs = registry::load_installed();
        auto it = recs.find("vcpkg");
        if (it != recs.end() && !it->second.toolchain_dir.empty()) {
            fs::path vcpkg_root = paths::toolchain_dir(it->second.toolchain_dir);
            if (win_path::set_user_env("VCPKG_ROOT", vcpkg_root.string())) {
                log::okf("set HKCU VCPKG_ROOT = {}", vcpkg_root.string());
            }
        } else {
            log::info("VCPKG_ROOT not set (no vcpkg in registry; run `luban setup --only vcpkg` first)");
        }

        log::info("open a new shell for the changes to take effect.");
    }

    // --unset-user：从 HKCU PATH 移除（撤销 rustup-style 注入）。
    if (get_flag("unset-user")) {
        if (win_path::remove_from_user_path(bin)) {
            log::okf("removed {} from HKCU PATH", bin.string());
        } else {
            log::infof("{} not on HKCU PATH (nothing to do)", bin.string());
        }
        for (auto& [k, _] : env_snapshot::env_dict()) win_path::unset_user_env(k);
        win_path::unset_user_env("VCPKG_ROOT");
        log::ok("removed LUBAN_* and VCPKG_ROOT from HKCU env");
    }

    return 0;
}

}  // namespace

void register_env() {
    cli::Subcommand c;
    c.name = "env";
    c.help = "show env state; activate scripts; register HKCU PATH (rustup-style)";
    c.group = "setup";
    c.long_help =
        "  Manage environment integration. With no flags, prints status.\n"
        "\n"
        "  --user      Register <data>/bin/ on HKCU PATH + set HKCU env\n"
        "              vars (LUBAN_DATA, VCPKG_ROOT, etc.). After running\n"
        "              this once, any new shell can run cmake/clang/ninja\n"
        "              directly without `call activate.cmd`.\n"
        "  --unset-user  Reverse the above.\n"
        "  --apply     Rewrite <data>/env/activate.{cmd,ps1,sh} from current registry.";
    c.flags = {"apply", "user", "unset-user"};
    c.examples = {
        "luban env\tShow current env state",
        "luban env --user\tOne-time HKCU PATH registration (rustup-style)",
        "luban env --unset-user\tUndo the above",
    };
    c.run = run_env;
    cli::register_subcommand(std::move(c));
}

}  // namespace luban::commands
