#include "env_snapshot.hpp"

#include <algorithm>
#include <cstdlib>
#include <set>
#include <string>

#include "msvc_env.hpp"
#include "paths.hpp"
#include "registry.hpp"

namespace luban::env_snapshot {

namespace {

#ifdef _WIN32
constexpr char kPathSep = ';';
#else
constexpr char kPathSep = ':';
#endif

std::string lower(const std::string& s) {
    std::string out(s);
    std::transform(out.begin(), out.end(), out.begin(),
                   [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
    return out;
}

}  // namespace

std::vector<fs::path> path_dirs() {
    std::set<std::string> seen;
    std::vector<fs::path> ordered;
    auto add = [&](const fs::path& p) {
        std::error_code ec;
        if (!fs::exists(p, ec)) return;
#ifdef _WIN32
        std::string key = lower(p.string());
#else
        std::string key = p.string();
#endif
        if (!seen.insert(key).second) return;
        ordered.push_back(p);
    };

    auto recs = registry::load_installed();
    for (auto& [_, rec] : recs) {
        fs::path root = paths::toolchain_dir(rec.toolchain_dir);
        for (auto& [alias, rel] : rec.bins) {
            // Normalize separators — bin entries are stored with '/' on disk.
            std::string norm = rel;
            for (auto& c : norm) if (c == '/' || c == '\\') c = static_cast<char>(fs::path::preferred_separator);
            fs::path exe = root / norm;
            add(exe.parent_path());
        }
    }
    add(paths::bin_dir());

    // MSVC tool dirs (when --msvc-init has been run). Without these,
    // which_search wouldn't be able to resolve `luban run cl ...` even
    // though apply_to puts them on PATH for the spawned cmake. Splitting
    // path_addition by ';' (Windows separator) into individual entries.
    if (auto cap = msvc_env::load(); cap && !cap->path_addition.empty()) {
        std::string s = cap->path_addition;
        size_t start = 0;
        while (start <= s.size()) {
            size_t end = s.find(';', start);
            if (end == std::string::npos) end = s.size();
            std::string dir = s.substr(start, end - start);
            if (!dir.empty()) add(fs::path(dir));
            if (end == s.size()) break;
            start = end + 1;
        }
    }

    return ordered;
}

std::vector<std::pair<std::string, std::string>> env_dict() {
    // Vars luban spawn-children should see beyond plain PATH:
    //
    //   VCPKG_ROOT — CMakePresets.json generated by `luban new` references
    //                $env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake.
    //                Was missing here in v0.1.x (only set in HKCU by env
    //                --user); luban-spawned cmake without env --user
    //                couldn't find vcpkg. This fixes that.
    //
    //   VCPKG_DOWNLOADS / VCPKG_DEFAULT_BINARY_CACHE / X_VCPKG_REGISTRIES_CACHE
    //                Route vcpkg's own caches into <cache>/vcpkg/* instead
    //                of vcpkg's scattered defaults. One place to clear
    //                everything.
    //
    //   EM_CONFIG  — emscripten reads its python-style config from this
    //                path. We write the file at install time (component.cpp
    //                emscripten special case) and tell every spawned shell
    //                here so `emcc` works without a per-shell setup step.
    std::vector<std::pair<std::string, std::string>> out;

    auto recs = registry::load_installed();
    auto vcpkg_it = recs.find("vcpkg");
    if (vcpkg_it != recs.end() && !vcpkg_it->second.toolchain_dir.empty()) {
        out.emplace_back("VCPKG_ROOT",
                         paths::toolchain_dir(vcpkg_it->second.toolchain_dir).string());
    }

    fs::path vcpkg_cache = paths::cache_dir() / "vcpkg";
    out.emplace_back("VCPKG_DOWNLOADS",            (vcpkg_cache / "downloads").string());
    out.emplace_back("VCPKG_DEFAULT_BINARY_CACHE", (vcpkg_cache / "archives").string());
    out.emplace_back("X_VCPKG_REGISTRIES_CACHE",   (vcpkg_cache / "registries").string());

    if (recs.find("emscripten") != recs.end()) {
        out.emplace_back("EM_CONFIG",
                         (paths::config_dir() / "emscripten" / "config").string());
    }

    // MSVC: if the user ran `luban env --msvc-init`, the captured INCLUDE /
    // LIB / LIBPATH / WindowsSdk* / VCToolsInstallDir / etc. live in
    // <state>/msvc-env.json. Merge them so luban-spawned cmake can drive
    // cl.exe without the user sourcing vcvarsall first. PATH addition is
    // handled separately in apply_to() so it merges cleanly with luban's
    // own PATH overlay.
    if (auto cap = msvc_env::load()) {
        for (auto& [k, v] : cap->vars) out.emplace_back(k, v);
    }

    return out;
}

std::map<std::string, std::string> apply_to(const std::map<std::string, std::string>& env) {
    std::map<std::string, std::string> out;

    // path_dirs() already includes MSVC tool dirs when --msvc-init has been
    // run, so we just join + prepend onto whatever PATH the caller had.
    auto extras = path_dirs();
    if (!extras.empty()) {
        std::string joined;
        for (size_t i = 0; i < extras.size(); ++i) {
            if (i) joined.push_back(kPathSep);
            joined += extras[i].string();
        }
        // existing PATH: env arg first, fall back to current process env.
        // Critical — child cmake / vcpkg need C:\Windows\System32 etc. to
        // find ninja / system DLLs.
        std::string existing;
        auto it = env.find("PATH");
        if (it != env.end()) {
            existing = it->second;
        } else if (const char* p = std::getenv("PATH"); p && *p) {
            existing = p;
        }
        out["PATH"] = existing.empty() ? joined : (joined + kPathSep + existing);
    }
    for (auto& [k, v] : env_dict()) out[k] = v;
    return out;
}

}  // namespace luban::env_snapshot
