#include "luban_cmake_gen.hpp"

#include <algorithm>
#include <fstream>
#include <set>
#include <sstream>
#include <system_error>

#include "lib_targets.hpp"
#include "log.hpp"

namespace luban::luban_cmake_gen {

namespace {

std::string warning_flags(luban_toml::WarningLevel w) {
    switch (w) {
        case luban_toml::WarningLevel::Off:
            return "";
        case luban_toml::WarningLevel::Strict:
            return "-Wall -Wextra -Wpedantic -Werror=return-type";
        case luban_toml::WarningLevel::Normal:
        default:
            return "-Wall -Wextra";
    }
}

std::string sanitizer_flags(const std::vector<std::string>& sans) {
    if (sans.empty()) return "";
    std::string list;
    for (size_t i = 0; i < sans.size(); ++i) {
        if (i) list.push_back(',');
        list += sans[i];
    }
    return "-fsanitize=" + list;
}

}  // namespace

std::string render(const GenInputs& in) {
    std::ostringstream o;

    o << "# generated by luban — DO NOT EDIT BY HAND\n";
    o << "# regenerate via: luban add / remove / sync / target add / target remove\n";
    o << "# project deps come from vcpkg.json; flags come from luban.toml ([scaffold] section).\n";
    o << "\n";

    // ---- targets list ----
    o << "# ---- targets (LUBAN_TARGETS) ----\n";
    o << "set(LUBAN_TARGETS";
    for (auto& t : in.targets) o << " " << t;
    o << ")\n\n";

    // ---- find_package 块 ----
    // 收集 + 去重的 find_package 名（多个 boost-子库都映射到 Boost）。
    std::vector<std::string> find_pkgs;
    std::set<std::string> seen_find;
    std::vector<std::string> link_targets;

    for (const auto& dep : in.manifest.dependencies) {
        auto m = lib_targets::lookup(dep.name);
        if (m) {
            if (seen_find.insert(m->find_package_name).second) {
                find_pkgs.push_back(m->find_package_name);
            }
            for (auto& t : m->link_targets) link_targets.push_back(t);
        } else {
            // miss：用 vcpkg port 名直接试 find_package
            std::string fp = dep.name;
            // Replace '-' with '_' for cmake-friendly fallback
            if (seen_find.insert(fp).second) find_pkgs.push_back(fp);
            // link target 用户需要在 luban.toml [targets] 段或 src/<x>/CMakeLists.txt 自填
            // 这里写注释提示，不阻塞构建
        }
    }

    o << "# ---- find_package (auto from vcpkg.json dependencies) ----\n";
    if (find_pkgs.empty()) {
        o << "# (no dependencies declared)\n";
    } else {
        for (auto& p : find_pkgs) {
            o << "find_package(" << p << " CONFIG REQUIRED)\n";
        }
    }
    o << "\n";

    // ---- luban_apply ----
    o << "# ---- luban_apply: call once per target after add_executable / add_library ----\n";
    o << "function(luban_apply target)\n";
    o << "    target_compile_features(${target} PRIVATE cxx_std_" << in.toml.project.cpp << ")\n";

    std::string warns = warning_flags(in.toml.scaffold.warnings);
    std::string sans  = sanitizer_flags(in.toml.scaffold.sanitizers);
    o << "    if(NOT MSVC)\n";
    if (!warns.empty()) {
        o << "        target_compile_options(${target} PRIVATE";
        std::istringstream iss(warns);
        std::string flag;
        while (iss >> flag) o << " " << flag;
        o << ")\n";
    }
    if (!sans.empty()) {
        o << "        target_compile_options(${target} PRIVATE " << sans << ")\n";
        o << "        target_link_options(${target}    PRIVATE " << sans << ")\n";
    }
    // 静态链接 toolchain 运行时（默认）—— 让产物在裸 cmd 直接跑，
    // 不依赖 toolchain bin/ 在 PATH 上的 libc++.dll / libwinpthread-1.dll 等。
    // 用户想动态链接可在 src/<target>/CMakeLists.txt 里 target_link_options(... -shared-libgcc) 覆盖。
    o << "        # static-link toolchain runtime so the exe runs without toolchain DLLs on PATH.\n";
    o << "        target_link_options(${target} PRIVATE -static -static-libgcc -static-libstdc++)\n";
    o << "    endif()\n";

    if (!link_targets.empty()) {
        o << "    target_link_libraries(${target} PRIVATE\n";
        for (auto& t : link_targets) o << "        " << t << "\n";
        o << "    )\n";
    }

    o << "endfunction()\n\n";

    // ---- luban_register_targets ----
    o << "# ---- luban_register_targets: call once from root CMakeLists.txt ----\n";
    o << "function(luban_register_targets)\n";
    o << "    foreach(t IN LISTS LUBAN_TARGETS)\n";
    o << "        if(EXISTS ${CMAKE_SOURCE_DIR}/src/${t}/CMakeLists.txt)\n";
    o << "            add_subdirectory(src/${t})\n";
    o << "        else()\n";
    o << "            message(WARNING \"luban: target '${t}' has no src/${t}/CMakeLists.txt; skipping\")\n";
    o << "        endif()\n";
    o << "    endforeach()\n";
    o << "endfunction()\n";

    return o.str();
}

void regenerate_in_project(const fs::path& project_dir,
                           const std::vector<std::string>& targets) {
    GenInputs in;
    in.toml = luban_toml::load(project_dir / "luban.toml");
    in.manifest = vcpkg_manifest::load(project_dir / "vcpkg.json");
    in.targets = targets;

    std::string content = render(in);

    fs::path out = project_dir / "luban.cmake";
    std::error_code ec;
    fs::path tmp = out; tmp += ".tmp";
    {
        std::ofstream of(tmp, std::ios::binary | std::ios::trunc);
        of.write(content.data(), static_cast<std::streamsize>(content.size()));
    }
    fs::rename(tmp, out, ec);
    if (ec) {
        fs::copy_file(tmp, out, fs::copy_options::overwrite_existing, ec);
        fs::remove(tmp, ec);
    }
}

std::vector<std::string> read_targets_from_cmake(const fs::path& project_dir) {
    std::vector<std::string> out;
    std::ifstream in(project_dir / "luban.cmake", std::ios::binary);
    if (!in) return out;

    std::string line;
    while (std::getline(in, line)) {
        // 找 set(LUBAN_TARGETS ...) 行（忽略前导空白）
        size_t p = line.find_first_not_of(" \t");
        if (p == std::string::npos) continue;
        if (line.compare(p, 4, "set(") != 0) continue;
        // 解析 set(LUBAN_TARGETS foo bar baz)
        size_t open = line.find('(', p);
        size_t close = line.find(')', open == std::string::npos ? p : open);
        if (open == std::string::npos || close == std::string::npos) continue;
        std::string body = line.substr(open + 1, close - open - 1);
        std::istringstream iss(body);
        std::string head;
        if (!(iss >> head) || head != "LUBAN_TARGETS") continue;
        std::string tok;
        while (iss >> tok) out.push_back(tok);
        return out;  // 只取第一个 set(LUBAN_TARGETS ...)
    }
    return out;
}

}  // namespace luban::luban_cmake_gen
