# Embed a text file as a C++ raw string literal in a generated header.
#
# Used by luban for two embed cases:
#  - templates/help/<verb>.md → luban::embedded_help::<verb>_help (long
#    --help output for setup / new / specs verbs)
#  - templates/configs/<X>.lua → luban::embedded_configs::<X>_lua
#    (per-tool renderer modules for [config.X] blocks)
#
# Build-time embed via `R"<sentinel>(...)"` keeps the source file and
# the binary's view in lockstep — bump the file, rebuild, the binary
# follows.
#
# Usage from a parent CMakeLists.txt:
#
#     set(GEN_DIR "${CMAKE_BINARY_DIR}/gen/luban/embedded_help")
#     add_custom_command(
#         OUTPUT  "${GEN_DIR}/specs.hpp"
#         COMMAND "${CMAKE_COMMAND}"
#                 -DINPUT=${CMAKE_SOURCE_DIR}/templates/help/specs.md
#                 -DOUTPUT=${GEN_DIR}/specs.hpp
#                 -DSYMBOL=specs_help
#                 -DNAMESPACE=luban::embedded_help    # optional, defaults
#                 -P ${CMAKE_SOURCE_DIR}/cmake/embed_text.cmake
#         DEPENDS ${CMAKE_SOURCE_DIR}/templates/help/specs.md
#                 ${CMAKE_SOURCE_DIR}/cmake/embed_text.cmake)
#
# This file runs in cmake -P script mode (no project context). The caller
# passes INPUT / OUTPUT / SYMBOL (and optionally NAMESPACE) via -D.
#
# Sentinel: we use `R"LUBAN_EMBED(...)LUBAN_EMBED"`. The input is required
# NOT to contain the literal `)LUBAN_EMBED"` string (in practice neither
# markdown nor Lua will).

if(NOT INPUT)
    message(FATAL_ERROR "embed_text.cmake: INPUT is required")
endif()
if(NOT OUTPUT)
    message(FATAL_ERROR "embed_text.cmake: OUTPUT is required")
endif()
if(NOT SYMBOL)
    message(FATAL_ERROR "embed_text.cmake: SYMBOL is required")
endif()
if(NOT NAMESPACE)
    set(NAMESPACE "luban::embedded_help")
endif()

file(READ "${INPUT}" CONTENT)

# Defensive: refuse to proceed if the sentinel appears verbatim in the
# input. With markdown / Lua content that's astronomically unlikely, but
# the error message is more useful than silently producing broken C++.
if(CONTENT MATCHES "\\)LUBAN_EMBED\"")
    message(FATAL_ERROR
        "embed_text.cmake: ${INPUT} contains the literal close-sentinel "
        "`)LUBAN_EMBED\"` which would break the raw string literal. "
        "Rename or escape it.")
endif()

set(HEADER "// Generated by cmake/embed_text.cmake from ${INPUT}.\n")
set(HEADER "${HEADER}// DO NOT EDIT — change the source file and rebuild.\n\n")
set(HEADER "${HEADER}#pragma once\n\n")
set(HEADER "${HEADER}namespace ${NAMESPACE} {\n\n")
set(HEADER "${HEADER}inline constexpr const char* ${SYMBOL} = R\"LUBAN_EMBED(")
set(FOOTER ")LUBAN_EMBED\";\n\n}  // namespace ${NAMESPACE}\n")

file(WRITE "${OUTPUT}" "${HEADER}${CONTENT}${FOOTER}")
