# Embed a text file as a C++ raw string literal in a generated header.
#
# Used by luban's "manual-grade long_help" subsystem: a single markdown
# file serves as both (1) the mdBook chapter at docs/src/commands/<verb>.md
# and (2) the `luban <verb> --help` long-form output. Build-time embed via
# `R"<sentinel>(...)"` keeps the two views in lockstep — bump the .md, the
# binary's --help follows on next rebuild.
#
# Usage from a parent CMakeLists.txt:
#
#     set(GEN_DIR "${CMAKE_BINARY_DIR}/gen/luban/embedded_help")
#     add_custom_command(
#         OUTPUT  "${GEN_DIR}/specs.hpp"
#         COMMAND "${CMAKE_COMMAND}"
#                 -DINPUT=${CMAKE_SOURCE_DIR}/docs/src/commands/specs.md
#                 -DOUTPUT=${GEN_DIR}/specs.hpp
#                 -DSYMBOL=specs_help
#                 -P ${CMAKE_SOURCE_DIR}/cmake/embed_text.cmake
#         DEPENDS ${CMAKE_SOURCE_DIR}/docs/src/commands/specs.md
#                 ${CMAKE_SOURCE_DIR}/cmake/embed_text.cmake)
#
# This file runs in cmake -P script mode (no project context). The caller
# passes INPUT / OUTPUT / SYMBOL via -D.
#
# Sentinel: we use `R"LUBAN_EMBED(...)LUBAN_EMBED"`. The .md is required
# NOT to contain the literal `)LUBAN_EMBED"` string (in practice, no
# markdown will).

if(NOT INPUT)
    message(FATAL_ERROR "embed_text.cmake: INPUT is required")
endif()
if(NOT OUTPUT)
    message(FATAL_ERROR "embed_text.cmake: OUTPUT is required")
endif()
if(NOT SYMBOL)
    message(FATAL_ERROR "embed_text.cmake: SYMBOL is required")
endif()

file(READ "${INPUT}" CONTENT)

# Defensive: refuse to proceed if the sentinel appears verbatim in the
# input. With markdown content that's astronomically unlikely, but the
# error message is more useful than silently producing broken C++.
if(CONTENT MATCHES "\\)LUBAN_EMBED\"")
    message(FATAL_ERROR
        "embed_text.cmake: ${INPUT} contains the literal close-sentinel "
        "`)LUBAN_EMBED\"` which would break the raw string literal. "
        "Rename or escape it.")
endif()

set(HEADER "// Generated by cmake/embed_text.cmake from ${INPUT}.\n")
set(HEADER "${HEADER}// DO NOT EDIT — change the source .md and rebuild.\n\n")
set(HEADER "${HEADER}#pragma once\n\n")
set(HEADER "${HEADER}namespace luban::embedded_help {\n\n")
set(HEADER "${HEADER}inline constexpr const char* ${SYMBOL} = R\"LUBAN_EMBED(")
set(FOOTER ")LUBAN_EMBED\";\n\n}  // namespace luban::embedded_help\n")

file(WRITE "${OUTPUT}" "${HEADER}${CONTENT}${FOOTER}")
