Luban API Reference: luban::hash Namespace Reference
luban::hash Namespace Reference
Classes
struct HashSpec
Enumerations
enum class Algorithm { Sha256 , Sha512 , Md5 , Sha1 }
Functions
std::string algo_name (Algorithm a)
std::optional< Algorithm > parse_algo (std::string_view name)
std::optional< HashSpec > parse (std::string_view raw)
std::string to_string (const HashSpec &spec)
std::optional< HashSpec > hash_file (const fs::path &path, Algorithm algo)
bool verify_file (const fs::path &path, const HashSpec &expected)
Enumeration Type Documentation
Algorithm
enum class luban::hash::Algorithm strong
Enumerator
Sha256
Sha512
Md5
Sha1
Definition at line 14 of file hash.hpp.
Function Documentation
algo_name()
std::string luban::hash::algo_name (Algorithm a)
Definition at line 59 of file hash.cpp.
References Md5, Sha1, Sha256, and Sha512.
Referenced by to_string().
hash_file()
std::optional< HashSpec > luban::hash::hash_file (const fs::path & path, Algorithm algo)
Definition at line 114 of file hash.cpp.
References alg, Md5, path, Sha1, Sha256, and Sha512.
Referenced by verify_file().
parse()
std::optional< HashSpec > luban::hash::parse (std::string_view raw)
Definition at line 80 of file hash.cpp.
References parse_algo(), and Sha256.
Referenced by luban::component::install().
parse_algo()
std::optional< Algorithm > luban::hash::parse_algo (std::string_view name)
Definition at line 69 of file hash.cpp.
References Md5, name, Sha1, Sha256, and Sha512.
Referenced by parse().
to_string()
std::string luban::hash::to_string (const HashSpec & spec)
Definition at line 110 of file hash.cpp.
References luban::hash::HashSpec::algo, algo_name(), and luban::hash::HashSpec::hex.
verify_file()
bool luban::hash::verify_file (const fs::path & path, const HashSpec & expected)
Definition at line 209 of file hash.cpp.
References luban::hash::HashSpec::algo, hash_file(), luban::hash::HashSpec::hex, and path.
Referenced by luban::component::install().