Luban API Reference: luban::cli Namespace Reference
luban::cli Namespace Reference
Classes
struct ParsedArgs
struct Subcommand
Functions
void register_subcommand (Subcommand cmd)
int dispatch (int argc, char **argv)
Function Documentation
dispatch()
int luban::cli::dispatch (int argc, char ** argv)
Definition at line 199 of file cli.cpp.
References luban::log::errf(), luban::cli::Subcommand::n_positional, luban::cli::Subcommand::name, luban::cli::ParsedArgs::opts, luban::cli::ParsedArgs::positional, luban::cli::Subcommand::run, and luban::log::set_verbose().
register_subcommand()
void luban::cli::register_subcommand (Subcommand cmd)
Definition at line 195 of file cli.cpp.
Referenced by luban::commands::register_add(), luban::commands::register_build(), luban::commands::register_describe(), luban::commands::register_doc(), luban::commands::register_doctor(), luban::commands::register_env(), luban::commands::register_new(), luban::commands::register_remove(), luban::commands::register_run(), luban::commands::register_search(), luban::commands::register_self(), luban::commands::register_setup(), luban::commands::register_shim(), luban::commands::register_specs(), luban::commands::register_sync(), luban::commands::register_target(), and luban::commands::register_which().