Luban API Reference: luban::selection Namespace Reference
luban::selection Namespace Reference
Classes
struct Entry
struct Selection
Functions
Selection load (bool deploy_seed)
void save (const Selection &sel)
bool enable (Selection &sel, const std::string &name)
bool disable (Selection &sel, const std::string &name)
std::vector< fs::path > deploy_overlays ()
Function Documentation
deploy_overlays()
std::vector< fs::path > luban::selection::deploy_overlays ()
Definition at line 158 of file selection.cpp.
References luban::paths::overlay_dir(), luban::file_util::read_text_no_bom(), and luban::file_util::write_text_atomic().
disable()
bool luban::selection::disable (Selection & sel, const std::string & name)
Definition at line 145 of file selection.cpp.
References luban::selection::Selection::components, luban::selection::Selection::extras, and name.
enable()
bool luban::selection::enable (Selection & sel, const std::string & name)
Definition at line 128 of file selection.cpp.
References luban::selection::Selection::components, luban::selection::Entry::enabled, luban::selection::Selection::extras, name, and luban::selection::Entry::name.
load()
Selection luban::selection::load (bool deploy_seed)
Definition at line 72 of file selection.cpp.
References luban::selection::Selection::components, luban::selection::Selection::extras, luban::file_util::read_text_no_bom(), luban::paths::selection_json_path(), and luban::file_util::write_text_atomic().
save()
void luban::selection::save (const Selection & sel)
Definition at line 115 of file selection.cpp.
References luban::selection::Selection::components, luban::selection::Selection::extras, luban::paths::selection_json_path(), and luban::file_util::write_text_atomic().