Luban API Reference: luban::msvc_env Namespace Reference
luban::msvc_env Namespace Reference
Classes
struct Captured
Functions
fs::path file_path ()
fs::path find_vswhere ()
fs::path find_install ()
fs::path find_vcvarsall (const fs::path &install_path)
std::optional< Captured > capture (const fs::path &install_path, const std::string &arch)
bool save (const Captured &c)
std::optional< Captured > load ()
void clear ()
Function Documentation
capture()
std::optional< Captured > luban::msvc_env::capture (const fs::path & install_path, const std::string & arch)
Definition at line 195 of file msvc_env.cpp.
References luban::msvc_env::Captured::arch, luban::msvc_env::Captured::captured_at, luban::log::err(), luban::log::errf(), find_vcvarsall(), luban::msvc_env::Captured::path_addition, luban::msvc_env::Captured::vars, and luban::msvc_env::Captured::vs_install_path.
clear()
void luban::msvc_env::clear ()
Definition at line 292 of file msvc_env.cpp.
References file_path().
file_path()
fs::path luban::msvc_env::file_path ()
Definition at line 154 of file msvc_env.cpp.
References luban::paths::state_dir().
Referenced by clear(), load(), and save().
find_install()
fs::path luban::msvc_env::find_install ()
Definition at line 170 of file msvc_env.cpp.
References find_vswhere().
find_vcvarsall()
fs::path luban::msvc_env::find_vcvarsall (const fs::path & install_path)
Definition at line 188 of file msvc_env.cpp.
Referenced by capture().
find_vswhere()
fs::path luban::msvc_env::find_vswhere ()
Definition at line 156 of file msvc_env.cpp.
References luban::paths::from_env().
Referenced by find_install().
load()
std::optional< Captured > luban::msvc_env::load ()
Definition at line 269 of file msvc_env.cpp.
References luban::msvc_env::Captured::arch, luban::msvc_env::Captured::captured_at, file_path(), luban::msvc_env::Captured::path_addition, luban::file_util::read_text_no_bom(), luban::msvc_env::Captured::vars, and luban::msvc_env::Captured::vs_install_path.
Referenced by luban::env_snapshot::env_dict(), and luban::env_snapshot::path_dirs().
save()
bool luban::msvc_env::save (const Captured & c)
Definition at line 252 of file msvc_env.cpp.
References luban::msvc_env::Captured::arch, luban::msvc_env::Captured::captured_at, file_path(), luban::msvc_env::Captured::path_addition, luban::msvc_env::Captured::vars, luban::msvc_env::Captured::vs_install_path, and luban::file_util::write_text_atomic().