Luban API Reference: luban::win Namespace Reference
luban::win Namespace Reference
Functions
std::wstring from_utf8 (std::string_view s)
std::string to_utf8 (std::wstring_view s)
Function Documentation
from_utf8()
std::wstring luban::win::from_utf8 (std::string_view s) inline
Definition at line 17 of file win.hpp.
Referenced by luban::win_path::add_to_user_path(), luban::path_search::on_path(), luban::win_path::remove_from_user_path(), luban::proc::run(), luban::win_path::set_user_env(), and luban::win_path::unset_user_env().
to_utf8()
std::string luban::win::to_utf8 (std::wstring_view s) inline
Definition at line 27 of file win.hpp.
Referenced by luban::path_search::on_path(), and luban::win_path::read_user_path().