Luban API Reference: luban::luban_toml Namespace Reference
luban::luban_toml Namespace Reference
Classes
struct Config
struct ProjectSection
struct ScaffoldSection
Typedefs
using ToolchainPins = std::map< std::string, std::string >
Enumerations
enum class WarningLevel { Off , Normal , Strict }
Functions
Config load (const fs::path &path)
Config load_from_text (const std::string &text)
Typedef Documentation
ToolchainPins
using luban::luban_toml::ToolchainPins = typedef std::map<std::string, std::string>
Definition at line 48 of file luban_toml.hpp.
Enumeration Type Documentation
WarningLevel
enum class luban::luban_toml::WarningLevel strong
Enumerator
Off
Normal
Strict
Definition at line 22 of file luban_toml.hpp.
Function Documentation
load()
Config luban::luban_toml::load (const fs::path & path)
Definition at line 100 of file luban_toml.cpp.
References path, and luban::log::warnf().
Referenced by luban::luban_cmake_gen::regenerate_in_project().
load_from_text()
Config luban::luban_toml::load_from_text (const std::string & text)
Definition at line 114 of file luban_toml.cpp.
References luban::log::warnf().