Luban API Reference: luban::vcpkg_manifest Namespace Reference
luban::vcpkg_manifest Namespace Reference
Classes
struct Dependency
struct Manifest
Functions
Manifest load (const fs::path &path, const std::string &fallback_name)
void save (const fs::path &path, const Manifest &m)
void add (Manifest &m, const std::string &pkg, const std::string &version_ge)
bool remove (Manifest &m, const std::string &pkg)
std::pair< std::string, std::string > parse_pkg_spec (const std::string &spec)
Function Documentation
add()
void luban::vcpkg_manifest::add (Manifest & m, const std::string & pkg, const std::string & version_ge)
Definition at line 113 of file vcpkg_manifest.cpp.
References luban::vcpkg_manifest::Manifest::dependencies, luban::vcpkg_manifest::Dependency::name, and luban::vcpkg_manifest::Dependency::version_ge.
load()
Manifest luban::vcpkg_manifest::load (const fs::path & path, const std::string & fallback_name)
Definition at line 30 of file vcpkg_manifest.cpp.
References luban::vcpkg_manifest::Manifest::dependencies, luban::vcpkg_manifest::Manifest::extras, luban::vcpkg_manifest::Dependency::name, luban::vcpkg_manifest::Manifest::name, path, luban::file_util::read_text_no_bom(), luban::vcpkg_manifest::Manifest::version, and luban::vcpkg_manifest::Dependency::version_ge.
Referenced by luban::luban_cmake_gen::regenerate_in_project().
parse_pkg_spec()
std::pair< std::string, std::string > luban::vcpkg_manifest::parse_pkg_spec (const std::string & spec)
Definition at line 134 of file vcpkg_manifest.cpp.
remove()
bool luban::vcpkg_manifest::remove (Manifest & m, const std::string & pkg)
Definition at line 126 of file vcpkg_manifest.cpp.
References luban::vcpkg_manifest::Manifest::dependencies.
save()
void luban::vcpkg_manifest::save (const fs::path & path, const Manifest & m)
Definition at line 83 of file vcpkg_manifest.cpp.
References luban::vcpkg_manifest::Manifest::dependencies, luban::vcpkg_manifest::Manifest::extras, luban::vcpkg_manifest::Manifest::name, path, luban::vcpkg_manifest::Manifest::version, and luban::file_util::write_text_atomic().