Luban API Reference: luban::commands Namespace Reference
luban::commands Namespace Reference
Functions
void register_add ()
void register_remove ()
void register_sync ()
int build_project (const fs::path &project_dir)
void register_build ()
void register_completion ()
void register_describe ()
void register_doc ()
void register_doctor ()
void register_env ()
int build_project (const std::filesystem::path &project_dir)
void register_new ()
void register_self ()
void register_setup ()
void register_shim ()
void register_specs ()
void register_target ()
void register_run ()
void register_which ()
void register_search ()
Function Documentation
build_project() [1/2]
int luban::commands::build_project (const fs::path & project_dir)
Definition at line 224 of file build_project.cpp.
References luban::cli::ParsedArgs::opts.
build_project() [2/2]
int luban::commands::build_project (const std::filesystem::path & project_dir)
register_add()
void luban::commands::register_add ()
Definition at line 127 of file add.cpp.
References luban::cli::Subcommand::examples, luban::cli::Subcommand::group, luban::cli::Subcommand::help, luban::cli::Subcommand::long_help, luban::cli::Subcommand::n_positional, luban::cli::Subcommand::name, luban::cli::Subcommand::positional_names, luban::cli::register_subcommand(), and luban::cli::Subcommand::run.
register_build()
void luban::commands::register_build ()
Definition at line 231 of file build_project.cpp.
References luban::cli::Subcommand::examples, luban::cli::Subcommand::group, luban::cli::Subcommand::help, luban::cli::Subcommand::long_help, luban::cli::Subcommand::name, luban::cli::Subcommand::opts, luban::cli::register_subcommand(), and luban::cli::Subcommand::run.
register_completion()
void luban::commands::register_completion ()
Definition at line 408 of file completion.cpp.
register_describe()
void luban::commands::register_describe ()
Definition at line 250 of file describe.cpp.
References luban::cli::Subcommand::examples, luban::cli::Subcommand::flags, luban::cli::Subcommand::group, luban::cli::Subcommand::help, luban::cli::Subcommand::long_help, luban::cli::Subcommand::name, luban::cli::register_subcommand(), and luban::cli::Subcommand::run.
register_doc()
void luban::commands::register_doc ()
Definition at line 237 of file doc.cpp.
References luban::cli::Subcommand::examples, luban::cli::Subcommand::flags, luban::cli::Subcommand::group, luban::cli::Subcommand::help, luban::cli::Subcommand::long_help, luban::cli::Subcommand::name, luban::cli::register_subcommand(), and luban::cli::Subcommand::run.
register_doctor()
void luban::commands::register_doctor ()
Definition at line 221 of file doctor.cpp.
References luban::cli::Subcommand::examples, luban::cli::Subcommand::flags, luban::cli::Subcommand::group, luban::cli::Subcommand::help, luban::cli::Subcommand::long_help, luban::cli::Subcommand::name, luban::cli::register_subcommand(), and luban::cli::Subcommand::run.
register_env()
void luban::commands::register_env ()
Definition at line 319 of file env.cpp.
References luban::cli::Subcommand::examples, luban::cli::Subcommand::flags, luban::cli::Subcommand::group, luban::cli::Subcommand::help, luban::cli::Subcommand::long_help, luban::cli::Subcommand::name, luban::cli::Subcommand::opts, luban::cli::register_subcommand(), and luban::cli::Subcommand::run.
register_new()
void luban::commands::register_new ()
Definition at line 201 of file new_project.cpp.
References luban::cli::Subcommand::examples, luban::cli::Subcommand::flags, luban::cli::Subcommand::group, luban::cli::Subcommand::help, luban::cli::Subcommand::long_help, luban::cli::Subcommand::n_positional, luban::cli::Subcommand::name, luban::cli::Subcommand::opts, luban::cli::Subcommand::positional_names, luban::cli::register_subcommand(), and luban::cli::Subcommand::run.
register_remove()
void luban::commands::register_remove ()
Definition at line 151 of file add.cpp.
References luban::cli::Subcommand::examples, luban::cli::Subcommand::group, luban::cli::Subcommand::help, luban::cli::Subcommand::n_positional, luban::cli::Subcommand::name, luban::cli::Subcommand::positional_names, luban::cli::register_subcommand(), and luban::cli::Subcommand::run.
register_run()
void luban::commands::register_run ()
Definition at line 140 of file which_search.cpp.
References luban::cli::Subcommand::examples, luban::cli::Subcommand::forward_rest, luban::cli::Subcommand::group, luban::cli::Subcommand::help, luban::cli::Subcommand::long_help, luban::cli::Subcommand::name, luban::cli::register_subcommand(), and luban::cli::Subcommand::run.
register_search()
void luban::commands::register_search ()
Definition at line 189 of file which_search.cpp.
References luban::cli::Subcommand::examples, luban::cli::Subcommand::group, luban::cli::Subcommand::help, luban::cli::Subcommand::long_help, luban::cli::Subcommand::n_positional, luban::cli::Subcommand::name, luban::cli::Subcommand::positional_names, luban::cli::register_subcommand(), and luban::cli::Subcommand::run.
register_self()
void luban::commands::register_self ()
Definition at line 356 of file self.cpp.
References luban::cli::Subcommand::examples, luban::cli::Subcommand::flags, luban::cli::Subcommand::group, luban::cli::Subcommand::help, luban::cli::Subcommand::long_help, luban::cli::Subcommand::n_positional, luban::cli::Subcommand::name, luban::cli::Subcommand::positional_names, luban::cli::register_subcommand(), and luban::cli::Subcommand::run.
register_setup()
void luban::commands::register_setup ()
Definition at line 252 of file setup.cpp.
References luban::cli::Subcommand::examples, luban::cli::Subcommand::flags, luban::cli::Subcommand::group, luban::cli::Subcommand::help, luban::cli::Subcommand::long_help, luban::cli::Subcommand::name, luban::cli::Subcommand::opts, luban::cli::register_subcommand(), and luban::cli::Subcommand::run.
register_shim()
void luban::commands::register_shim ()
Definition at line 272 of file shim_cmd.cpp.
References luban::cli::Subcommand::examples, luban::cli::Subcommand::flags, luban::cli::Subcommand::group, luban::cli::Subcommand::help, luban::cli::Subcommand::long_help, luban::cli::Subcommand::name, luban::cli::register_subcommand(), and luban::cli::Subcommand::run.
register_specs()
void luban::commands::register_specs ()
Definition at line 478 of file specs.cpp.
References luban::cli::Subcommand::examples, luban::cli::Subcommand::group, luban::cli::Subcommand::help, luban::cli::Subcommand::long_help, luban::cli::Subcommand::n_positional, luban::cli::Subcommand::name, luban::cli::Subcommand::positional_names, luban::cli::register_subcommand(), and luban::cli::Subcommand::run.
register_sync()
void luban::commands::register_sync ()
Definition at line 165 of file add.cpp.
References luban::cli::Subcommand::examples, luban::cli::Subcommand::group, luban::cli::Subcommand::help, luban::cli::Subcommand::long_help, luban::cli::Subcommand::name, luban::cli::register_subcommand(), and luban::cli::Subcommand::run.
register_target()
void luban::commands::register_target ()
Definition at line 164 of file target.cpp.
References luban::cli::Subcommand::examples, luban::cli::Subcommand::group, luban::cli::Subcommand::help, luban::cli::Subcommand::long_help, luban::cli::Subcommand::n_positional, luban::cli::Subcommand::name, luban::cli::Subcommand::positional_names, luban::cli::register_subcommand(), and luban::cli::Subcommand::run.
register_which()
void luban::commands::register_which ()
Definition at line 167 of file which_search.cpp.
References luban::cli::Subcommand::examples, luban::cli::Subcommand::group, luban::cli::Subcommand::help, luban::cli::Subcommand::long_help, luban::cli::Subcommand::n_positional, luban::cli::Subcommand::name, luban::cli::Subcommand::positional_names, luban::cli::register_subcommand(), and luban::cli::Subcommand::run.