Luban API Reference: luban::env_snapshot Namespace Reference
luban::env_snapshot Namespace Reference
Functions
std::vector< fs::path > path_dirs ()
std::vector< std::pair< std::string, std::string > > env_dict ()
std::map< std::string, std::string > apply_to (const std::map< std::string, std::string > &env)
Function Documentation
apply_to()
std::map< std::string, std::string > luban::env_snapshot::apply_to (const std::map< std::string, std::string > & env)
Definition at line 139 of file env_snapshot.cpp.
References env_dict(), and path_dirs().
env_dict()
std::vector< std::pair< std::string, std::string > > luban::env_snapshot::env_dict ()
Definition at line 79 of file env_snapshot.cpp.
References luban::paths::config_dir(), luban::msvc_env::load(), luban::registry::load_installed(), luban::paths::toolchain_dir(), luban::paths::vcpkg_archives_dir(), luban::paths::vcpkg_downloads_dir(), and luban::paths::vcpkg_registries_dir().
Referenced by apply_to().
path_dirs()
std::vector< fs::path > luban::env_snapshot::path_dirs ()
Definition at line 31 of file env_snapshot.cpp.
References luban::paths::bin_dir(), luban::msvc_env::load(), luban::registry::load_installed(), and luban::paths::toolchain_dir().
Referenced by apply_to().