Luban API Reference: luban::luban_cmake_gen Namespace Reference
luban::luban_cmake_gen Namespace Reference
Classes
struct GenInputs
Functions
std::string render (const GenInputs &in)
void regenerate_in_project (const fs::path &project_dir, const std::vector< std::string > &targets)
std::vector< std::string > read_targets_from_cmake (const fs::path &project_dir)
Function Documentation
read_targets_from_cmake()
std::vector< std::string > luban::luban_cmake_gen::read_targets_from_cmake (const fs::path & project_dir)
Definition at line 159 of file luban_cmake_gen.cpp.
regenerate_in_project()
void luban::luban_cmake_gen::regenerate_in_project (const fs::path & project_dir, const std::vector< std::string > & targets)
Definition at line 136 of file luban_cmake_gen.cpp.
References luban::luban_toml::load(), luban::vcpkg_manifest::load(), luban::luban_cmake_gen::GenInputs::manifest, render(), targets, luban::luban_cmake_gen::GenInputs::targets, and luban::luban_cmake_gen::GenInputs::toml.
render()
std::string luban::luban_cmake_gen::render (const GenInputs & in)
Definition at line 40 of file luban_cmake_gen.cpp.
References luban::luban_toml::ProjectSection::cpp, luban::vcpkg_manifest::Manifest::dependencies, luban::lib_targets::lookup(), luban::luban_cmake_gen::GenInputs::manifest, luban::luban_toml::Config::project, luban::luban_toml::ScaffoldSection::sanitizers, luban::luban_toml::Config::scaffold, luban::luban_cmake_gen::GenInputs::targets, luban::luban_cmake_gen::GenInputs::toml, and luban::luban_toml::ScaffoldSection::warnings.
Referenced by regenerate_in_project().