Luban API Reference: luban::file_util Namespace Reference
luban::file_util Namespace Reference
Functions
std::string read_text (const fs::path &path)
std::string read_text_no_bom (const fs::path &path)
bool write_text_atomic (const fs::path &path, std::string_view content)
Function Documentation
read_text()
std::string luban::file_util::read_text (const fs::path & path)
Definition at line 35 of file file_util.cpp.
References path, and read_text().
Referenced by read_text().
read_text_no_bom()
std::string luban::file_util::read_text_no_bom (const fs::path & path)
Definition at line 39 of file file_util.cpp.
References path, and read_text_no_bom().
Referenced by luban::selection::deploy_overlays(), luban::msvc_env::load(), luban::selection::load(), luban::vcpkg_manifest::load(), luban::registry::load_installed(), and read_text_no_bom().
write_text_atomic()
bool luban::file_util::write_text_atomic (const fs::path & path, std::string_view content)
Definition at line 45 of file file_util.cpp.
References path, and write_text_atomic().
Referenced by luban::selection::deploy_overlays(), luban::selection::load(), luban::msvc_env::save(), luban::vcpkg_manifest::save(), luban::selection::save(), luban::registry::save_installed(), and write_text_atomic().