Luban API Reference: luban::win_path Namespace Reference
luban::win_path Namespace Reference
Functions
bool add_to_user_path (const fs::path &dir)
bool remove_from_user_path (const fs::path &dir)
std::vector< std::string > read_user_path ()
bool set_user_env (const std::string &name, const std::string &value, bool expand)
bool unset_user_env (const std::string &name)
Function Documentation
add_to_user_path()
bool luban::win_path::add_to_user_path (const fs::path & dir)
Definition at line 110 of file win_path.cpp.
References luban::win::from_utf8().
read_user_path()
std::vector< std::string > luban::win_path::read_user_path ()
Definition at line 154 of file win_path.cpp.
References luban::win::to_utf8().
remove_from_user_path()
bool luban::win_path::remove_from_user_path (const fs::path & dir)
Definition at line 134 of file win_path.cpp.
References luban::win::from_utf8().
set_user_env()
bool luban::win_path::set_user_env (const std::string & name, const std::string & value, bool expand)
Definition at line 165 of file win_path.cpp.
References luban::win::from_utf8(), and name.
unset_user_env()
bool luban::win_path::unset_user_env (const std::string & name)
Definition at line 191 of file win_path.cpp.
References luban::win::from_utf8(), and name.