Luban API Reference: luban::registry Namespace Reference
luban::registry Namespace Reference
Classes
struct AliasHit
struct ComponentRecord
Functions
std::map< std::string, ComponentRecord > load_installed ()
std::optional< AliasHit > resolve_alias (const std::string &alias)
void save_installed (const std::map< std::string, ComponentRecord > &records)
Function Documentation
load_installed()
std::map< std::string, ComponentRecord > luban::registry::load_installed ()
Definition at line 67 of file registry.cpp.
References luban::paths::installed_json_path(), name, and luban::file_util::read_text_no_bom().
Referenced by luban::env_snapshot::env_dict(), luban::component::install(), luban::env_snapshot::path_dirs(), resolve_alias(), and luban::component::uninstall().
resolve_alias()
std::optional< AliasHit > luban::registry::resolve_alias (const std::string & alias)
Definition at line 87 of file registry.cpp.
References luban::registry::AliasHit::alias, luban::registry::AliasHit::all_components, luban::registry::AliasHit::component, luban::registry::AliasHit::exe, load_installed(), and luban::paths::toolchain_dir().
save_installed()
void luban::registry::save_installed (const std::map< std::string, ComponentRecord > & records)
Definition at line 111 of file registry.cpp.
References luban::paths::installed_json_path(), name, and luban::file_util::write_text_atomic().
Referenced by luban::component::install(), and luban::component::uninstall().