Luban API Reference: luban::paths Namespace Reference
luban::paths Namespace Reference
Functions
std::optional< fs::path > from_env (std::string_view var)
fs::path home ()
fs::path data_dir ()
fs::path cache_dir ()
fs::path state_dir ()
fs::path config_dir ()
fs::path store_dir ()
fs::path store_sha256_dir ()
fs::path toolchains_dir ()
fs::path toolchain_dir (std::string_view name)
fs::path bin_dir ()
fs::path env_dir ()
fs::path registry_dir ()
fs::path buckets_dir ()
fs::path overlay_dir ()
fs::path downloads_dir ()
fs::path vcpkg_binary_cache_dir ()
fs::path vcpkg_cache_dir ()
fs::path vcpkg_downloads_dir ()
fs::path vcpkg_archives_dir ()
fs::path vcpkg_registries_dir ()
fs::path installed_json_path ()
fs::path last_sync_path ()
fs::path logs_dir ()
fs::path selection_json_path ()
fs::path config_toml_path ()
std::vector< std::pair< std::string, fs::path > > all_dirs ()
void ensure_dirs ()
bool same_volume (const fs::path &a, const fs::path &b)
Variables
constexpr std::string_view APP_NAME = "luban"
Function Documentation
all_dirs()
std::vector< std::pair< std::string, fs::path > > luban::paths::all_dirs ()
Definition at line 193 of file paths.cpp.
References bin_dir(), buckets_dir(), cache_dir(), config_dir(), data_dir(), downloads_dir(), env_dir(), logs_dir(), overlay_dir(), registry_dir(), state_dir(), store_dir(), store_sha256_dir(), toolchains_dir(), vcpkg_archives_dir(), vcpkg_binary_cache_dir(), vcpkg_downloads_dir(), and vcpkg_registries_dir().
Referenced by ensure_dirs().
bin_dir()
fs::path luban::paths::bin_dir ()
Definition at line 172 of file paths.cpp.
References data_dir().
Referenced by all_dirs(), luban::component::install(), luban::env_snapshot::path_dirs(), luban::shim::remove_shim(), and luban::shim::write_shim().
buckets_dir()
fs::path luban::paths::buckets_dir ()
Definition at line 175 of file paths.cpp.
References registry_dir().
Referenced by all_dirs().
cache_dir()
fs::path luban::paths::cache_dir ()
Definition at line 134 of file paths.cpp.
References APP_NAME, and home().
Referenced by all_dirs(), downloads_dir(), vcpkg_binary_cache_dir(), and vcpkg_cache_dir().
config_dir()
fs::path luban::paths::config_dir ()
Definition at line 148 of file paths.cpp.
References APP_NAME, and home().
Referenced by all_dirs(), config_toml_path(), luban::env_snapshot::env_dict(), luban::component::install(), and selection_json_path().
config_toml_path()
fs::path luban::paths::config_toml_path ()
Definition at line 191 of file paths.cpp.
References config_dir().
data_dir()
fs::path luban::paths::data_dir ()
Definition at line 127 of file paths.cpp.
References APP_NAME, and home().
Referenced by all_dirs(), bin_dir(), env_dir(), registry_dir(), store_dir(), and toolchains_dir().
downloads_dir()
fs::path luban::paths::downloads_dir ()
Definition at line 177 of file paths.cpp.
References cache_dir().
Referenced by all_dirs(), and luban::component::install().
ensure_dirs()
void luban::paths::ensure_dirs ()
Definition at line 216 of file paths.cpp.
References all_dirs().
Referenced by luban::component::install().
env_dir()
fs::path luban::paths::env_dir ()
Definition at line 173 of file paths.cpp.
References data_dir().
Referenced by all_dirs().
from_env()
std::optional< fs::path > luban::paths::from_env (std::string_view var)
Definition at line 104 of file paths.cpp.
Referenced by luban::msvc_env::find_vswhere().
home()
fs::path luban::paths::home ()
Definition at line 112 of file paths.cpp.
References h, and path.
Referenced by cache_dir(), config_dir(), data_dir(), luban::perception::snapshot(), and state_dir().
installed_json_path()
fs::path luban::paths::installed_json_path ()
Definition at line 187 of file paths.cpp.
References state_dir().
Referenced by luban::registry::load_installed(), and luban::registry::save_installed().
last_sync_path()
fs::path luban::paths::last_sync_path ()
Definition at line 188 of file paths.cpp.
References state_dir().
logs_dir()
fs::path luban::paths::logs_dir ()
Definition at line 189 of file paths.cpp.
References state_dir().
Referenced by all_dirs().
overlay_dir()
fs::path luban::paths::overlay_dir ()
Definition at line 176 of file paths.cpp.
References registry_dir().
Referenced by all_dirs(), luban::selection::deploy_overlays(), and luban::manifest_source::load().
registry_dir()
fs::path luban::paths::registry_dir ()
Definition at line 174 of file paths.cpp.
References data_dir().
Referenced by all_dirs(), buckets_dir(), and overlay_dir().
same_volume()
bool luban::paths::same_volume (const fs::path & a, const fs::path & b)
Definition at line 221 of file paths.cpp.
selection_json_path()
fs::path luban::paths::selection_json_path ()
Definition at line 190 of file paths.cpp.
References config_dir().
Referenced by luban::selection::load(), and luban::selection::save().
state_dir()
fs::path luban::paths::state_dir ()
Definition at line 141 of file paths.cpp.
References APP_NAME, and home().
Referenced by all_dirs(), luban::msvc_env::file_path(), installed_json_path(), last_sync_path(), and logs_dir().
store_dir()
fs::path luban::paths::store_dir ()
Definition at line 159 of file paths.cpp.
References data_dir().
Referenced by all_dirs(), and store_sha256_dir().
store_sha256_dir()
fs::path luban::paths::store_sha256_dir ()
Definition at line 160 of file paths.cpp.
References store_dir().
Referenced by all_dirs().
toolchain_dir()
fs::path luban::paths::toolchain_dir (std::string_view name)
Definition at line 162 of file paths.cpp.
References name, and toolchains_dir().
Referenced by luban::env_snapshot::env_dict(), luban::component::install(), luban::env_snapshot::path_dirs(), and luban::registry::resolve_alias().
toolchains_dir()
fs::path luban::paths::toolchains_dir ()
Definition at line 161 of file paths.cpp.
References data_dir().
Referenced by all_dirs(), toolchain_dir(), and luban::component::uninstall().
vcpkg_archives_dir()
fs::path luban::paths::vcpkg_archives_dir ()
Definition at line 185 of file paths.cpp.
References vcpkg_cache_dir().
Referenced by all_dirs(), and luban::env_snapshot::env_dict().
vcpkg_binary_cache_dir()
fs::path luban::paths::vcpkg_binary_cache_dir ()
Definition at line 178 of file paths.cpp.
References cache_dir().
Referenced by all_dirs().
vcpkg_cache_dir()
fs::path luban::paths::vcpkg_cache_dir ()
Definition at line 183 of file paths.cpp.
References cache_dir().
Referenced by vcpkg_archives_dir(), vcpkg_downloads_dir(), and vcpkg_registries_dir().
vcpkg_downloads_dir()
fs::path luban::paths::vcpkg_downloads_dir ()
Definition at line 184 of file paths.cpp.
References vcpkg_cache_dir().
Referenced by all_dirs(), and luban::env_snapshot::env_dict().
vcpkg_registries_dir()
fs::path luban::paths::vcpkg_registries_dir ()
Definition at line 186 of file paths.cpp.
References vcpkg_cache_dir().
Referenced by all_dirs(), and luban::env_snapshot::env_dict().
Variable Documentation
APP_NAME
constexpr std::string_view luban::paths::APP_NAME = "luban" constexpr
Definition at line 18 of file paths.hpp.
Referenced by cache_dir(), config_dir(), data_dir(), and state_dir().