Luban API Reference: luban::component Namespace Reference
luban::component Namespace Reference
Classes
struct Error
struct InstallReport
Enumerations
enum class ErrorKind {
ManifestNotFound , UnsafeManifest , IncompleteManifest , DownloadFailed ,
HashMismatch , ExtractFailed , Filesystem
}
Functions
std::expected< InstallReport, Error > install (const std::string &name, bool force, const std::string &arch)
bool uninstall (const std::string &name)
Enumeration Type Documentation
ErrorKind
enum class luban::component::ErrorKind strong
Enumerator
ManifestNotFound
UnsafeManifest
IncompleteManifest
DownloadFailed
HashMismatch
ExtractFailed
Filesystem
Definition at line 35 of file component.hpp.
Function Documentation
install()
std::expected< InstallReport, Error > luban::component::install (const std::string & name, bool force, const std::string & arch)
Definition at line 109 of file component.cpp.
References luban::registry::ComponentRecord::architecture, luban::scoop_manifest::ResolvedManifest::architecture, luban::paths::bin_dir(), luban::component::InstallReport::bins, luban::registry::ComponentRecord::bins, luban::scoop_manifest::ResolvedManifest::bins, luban::paths::config_dir(), luban::download::download(), DownloadFailed, luban::paths::downloads_dir(), luban::paths::ensure_dirs(), luban::scoop_manifest::ResolvedManifest::env_add_path, luban::download::DownloadOptions::expected_hash, luban::archive::extract(), ExtractFailed, Filesystem, luban::registry::ComponentRecord::hash_spec, luban::scoop_manifest::ResolvedManifest::hash_spec, HashMismatch, luban::download::HashMismatch, IncompleteManifest, luban::log::info(), luban::registry::ComponentRecord::installed_at, luban::download::DownloadOptions::label, luban::manifest_source::load(), luban::registry::load_installed(), ManifestNotFound, luban::component::Error::message, luban::scoop_manifest::ResolvedManifest::mirrors, name, luban::component::InstallReport::name, luban::registry::ComponentRecord::name, luban::scoop_manifest::ResolvedManifest::name, ok, luban::log::ok(), luban::log::okf(), luban::download::DownloadOptions::parallel_chunks, luban::scoop_manifest::parse(), luban::hash::parse(), luban::download::DownloadOptions::retries, luban::proc::run(), luban::registry::save_installed(), luban::shim::Skipped, luban::registry::ComponentRecord::source, luban::log::stepf(), luban::download::DownloadOptions::timeout_seconds, luban::component::InstallReport::toolchain_dir, luban::paths::toolchain_dir(), luban::registry::ComponentRecord::toolchain_dir, UnsafeManifest, luban::registry::ComponentRecord::url, luban::scoop_manifest::ResolvedManifest::url, luban::hash::verify_file(), luban::component::InstallReport::version, luban::registry::ComponentRecord::version, luban::scoop_manifest::ResolvedManifest::version, luban::log::warn(), luban::log::warnf(), luban::component::InstallReport::was_already_installed, and luban::shim::write_shim().
uninstall()
bool luban::component::uninstall (const std::string & name)
Definition at line 418 of file component.cpp.
References luban::registry::ComponentRecord::bins, luban::registry::load_installed(), name, luban::shim::remove_shim(), luban::registry::save_installed(), luban::registry::ComponentRecord::toolchain_dir, and luban::paths::toolchains_dir().