Luban API Reference: luban::shim Namespace Reference
luban::shim Namespace Reference
Enumerations
enum class WriteResult { Wrote , Skipped , Failed }
Functions
bool is_managed (const std::string &alias)
WriteResult write_shim (const std::string &alias, const fs::path &exe, const std::vector< std::string > &prefix_args, bool force)
int remove_shim (const std::string &alias)
Enumeration Type Documentation
WriteResult
enum class luban::shim::WriteResult strong
Enumerator
Wrote
Skipped
Failed
Definition at line 23 of file shim.hpp.
Function Documentation
is_managed()
bool luban::shim::is_managed (const std::string & alias)
Definition at line 82 of file shim.cpp.
Referenced by write_shim().
remove_shim()
int luban::shim::remove_shim (const std::string & alias)
Definition at line 113 of file shim.cpp.
References luban::paths::bin_dir().
Referenced by luban::component::uninstall().
write_shim()
WriteResult luban::shim::write_shim (const std::string & alias, const fs::path & exe, const std::vector< std::string > & prefix_args, bool force)
Definition at line 87 of file shim.cpp.
References luban::paths::bin_dir(), is_managed(), Skipped, and Wrote.
Referenced by luban::component::install().