Luban API Reference: luban::download Namespace Reference
luban::download Namespace Reference
Classes
struct DownloadOptions
struct DownloadResult
struct Error
Enumerations
enum class ErrorKind {
HttpClient , HttpServer , Network , HashMismatch ,
Io , Cancelled
}
Functions
std::expected< DownloadResult, Error > download (const std::string &url, const fs::path &dest, const DownloadOptions &opts)
std::expected< std::string, Error > fetch_text (const std::string &url, int timeout_seconds)
Enumeration Type Documentation
ErrorKind
enum class luban::download::ErrorKind strong
Enumerator
HttpClient
HttpServer
Network
HashMismatch
Io
Cancelled
Definition at line 26 of file download.hpp.
Function Documentation
download()
std::expected< DownloadResult, Error > luban::download::download (const std::string & url, const fs::path & dest, const DownloadOptions & opts)
Definition at line 702 of file download.cpp.
References luban::download::DownloadOptions::chunk_threshold, download(), luban::download::DownloadOptions::expected_hash, h, HttpClient, Io, label, luban::download::DownloadOptions::label, Network, luban::download::DownloadOptions::parallel_chunks, luban::download::DownloadOptions::retries, luban::download::DownloadOptions::timeout_seconds, total, and luban::log::warnf().
Referenced by download(), and luban::component::install().
fetch_text()
std::expected< std::string, Error > luban::download::fetch_text (const std::string & url, int timeout_seconds)
Definition at line 899 of file download.cpp.