Luban API Reference: luban::log Namespace Reference
luban::log Namespace Reference
Functions
void set_verbose (bool v)
bool is_verbose ()
std::string dim (std::string_view s)
std::string bold (std::string_view s)
std::string red (std::string_view s)
std::string green (std::string_view s)
std::string yellow (std::string_view s)
std::string blue (std::string_view s)
std::string cyan (std::string_view s)
void info (std::string_view msg)
void step (std::string_view msg)
void ok (std::string_view msg)
void warn (std::string_view msg)
void err (std::string_view msg)
void debug (std::string_view msg)
template<class... Args>
void infof (std::format_string< Args... > fmt, Args &&... args)
template<class... Args>
void stepf (std::format_string< Args... > fmt, Args &&... args)
template<class... Args>
void okf (std::format_string< Args... > fmt, Args &&... args)
template<class... Args>
void warnf (std::format_string< Args... > fmt, Args &&... args)
template<class... Args>
void errf (std::format_string< Args... > fmt, Args &&... args)
Function Documentation
blue()
std::string luban::log::blue (std::string_view s)
Definition at line 84 of file log.cpp.
Referenced by info().
bold()
std::string luban::log::bold (std::string_view s)
Definition at line 80 of file log.cpp.
Referenced by step().
cyan()
std::string luban::log::cyan (std::string_view s)
Definition at line 85 of file log.cpp.
Referenced by step().
debug()
void luban::log::debug (std::string_view msg)
Definition at line 92 of file log.cpp.
References dim().
dim()
std::string luban::log::dim (std::string_view s)
Definition at line 79 of file log.cpp.
Referenced by debug().
err()
void luban::log::err (std::string_view msg)
Definition at line 91 of file log.cpp.
References red().
Referenced by luban::msvc_env::capture(), and errf().
errf()
template<class... Args> void luban::log::errf (std::format_string< Args... > fmt, Args &&... args)
Definition at line 46 of file log.hpp.
References err().
Referenced by luban::msvc_env::capture(), and luban::cli::dispatch().
green()
std::string luban::log::green (std::string_view s)
Definition at line 82 of file log.cpp.
Referenced by ok().
info()
void luban::log::info (std::string_view msg)
Definition at line 87 of file log.cpp.
References blue().
Referenced by infof(), and luban::component::install().
infof()
template<class... Args> void luban::log::infof (std::format_string< Args... > fmt, Args &&... args)
Definition at line 30 of file log.hpp.
References info().
is_verbose()
bool luban::log::is_verbose ()
Definition at line 77 of file log.cpp.
ok()
void luban::log::ok (std::string_view msg)
Definition at line 89 of file log.cpp.
References green().
Referenced by luban::component::install().
okf()
template<class... Args> void luban::log::okf (std::format_string< Args... > fmt, Args &&... args)
Definition at line 38 of file log.hpp.
References ok.
Referenced by luban::component::install().
red()
std::string luban::log::red (std::string_view s)
Definition at line 81 of file log.cpp.
Referenced by err().
set_verbose()
void luban::log::set_verbose (bool v)
Definition at line 76 of file log.cpp.
Referenced by luban::cli::dispatch().
step()
void luban::log::step (std::string_view msg)
Definition at line 88 of file log.cpp.
References bold(), and cyan().
Referenced by stepf().
stepf()
template<class... Args> void luban::log::stepf (std::format_string< Args... > fmt, Args &&... args)
Definition at line 34 of file log.hpp.
References step().
Referenced by luban::component::install().
warn()
void luban::log::warn (std::string_view msg)
Definition at line 90 of file log.cpp.
References yellow().
Referenced by luban::component::install(), and warnf().
warnf()
template<class... Args> void luban::log::warnf (std::format_string< Args... > fmt, Args &&... args)
Definition at line 42 of file log.hpp.
References warn().
Referenced by luban::download::download(), luban::component::install(), luban::luban_toml::load(), luban::luban_toml::load_from_text(), and luban::marker_block::sync_managed_blocks().
yellow()
std::string luban::log::yellow (std::string_view s)
Definition at line 83 of file log.cpp.
Referenced by warn().